name: Gradle Package

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Set up JDK 17
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        check-latest: true

    # Step 3: Verify Java version
    - name: Verify Java version
      run: java -version

    # Step 4: Set JAVA_HOME explicitly
    - name: Set JAVA_HOME
      run: echo "JAVA_HOME=${{ steps.setup-java.outputs.java-home }}" >> $GITHUB_ENV

    # Step 5: Grant execute permissions to Gradle wrapper
    - name: Grant execute permission for Gradle wrapper
      run: chmod +x ./gradlew

    # Step 6: Debug Gradle environment
    - name: Debug Gradle Environment
      run: ./gradlew -version

    # Step 7: Build the project with Gradle
    - name: Build with Gradle
      uses: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25
      with:
        arguments: build

    # Step 8: Publish to GitHub Packages
    - name: Publish to GitHub Packages
      uses: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25
      with:
        arguments: publish
      env:
        GITHUB_ACTOR: ${{ github.actor }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # Step 9: Cleanup or post-build actions (optional)
    - name: Post-build cleanup
      run: echo "Build and publish steps completed."
